version: "3.9"
   
services:
  ecommerce:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    expose:
    - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    command:
      - /bin/sh
      - -c
      - |
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/backend
    environment:
      DJANGO_SECRET_KEY: 'fred'   # set to something in .env to enable debug toolbar
      # These are copied to the aws cloudformation files too
      DATABASE_HOST: ecommerce
      DATABASE_NAME: ecommerce
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8000:8000"
    depends_on:
      ecommerce:
        condition: service_healthy
    